Added last training sessions
ofahchouch-gh/gyro-project pull request #194
Opened 2021-06-09 15:18 UTC by Jelmerovereem

2021-06-09 15:20 UTC, StanBankras commented on www/src/views/Dashboard.vue
> +              <p>{{ training.patientFirstName.charAt(0) }}.{{ training.patientLastName }}</p>
What if the patient is anonymous or doesnt have a first or lastname?

2021-06-09 15:21 UTC, Jelmerovereem commented on www/src/views/Dashboard.vue
> +              <p>{{ training.patientFirstName.charAt(0) }}.{{ training.patientLastName }}</p>
Then we could show the unique identifier, is that part already implemented?

2021-06-09 15:21 UTC, StanBankras commented on www/src/store/index.js
> +        t.patientLastName = p.lastName
Why do you transform the keys? Isn't it logical to keep the same keys, so it remains consistent and we can work with it like any other training in the app?

2021-06-09 15:24 UTC, Jelmerovereem commented on www/src/store/index.js
> +        t.patientLastName = p.lastName
Because it's a training object, a training can't have a first & last name.
But I do understand the consistent thing. You suggest changing it to?:
```js
t.firstName = p.firstName
t.lastName = p.lastName
```

2021-06-09 15:25 UTC, StanBankras commented on www/src/views/Dashboard.vue
> +              <p>{{ training.patientFirstName.charAt(0) }}.{{ training.patientLastName }}</p>
I'm not sure, but until then you could implement a solution that would make integration really easy. Also fine to do that when the unique identifier is in though.

2021-06-09 15:26 UTC, StanBankras commented on www/src/store/index.js
> +        t.patientLastName = p.lastName
Yes, you're right, I forgot the training only holds the patientId and you actually have to add the names. I would say it's best to keep it consistent like that. yes.

2021-06-09 15:46 UTC, Jelmerovereem commented on www/src/views/Dashboard.vue
> +              <p>{{ training.patientFirstName.charAt(0) }}.{{ training.patientLastName }}</p>
https://github.com/ofahchouch-gh/gyro-project/blob/e348888dc0e7187258169b3c84f7f0f540ee8082/www/src/views/Dashboard.vue#L30-L41
This better?

2021-06-09 15:46 UTC, Jelmerovereem commented on www/src/store/index.js
> +        t.patientLastName = p.lastName
https://github.com/ofahchouch-gh/gyro-project/blob/e348888dc0e7187258169b3c84f7f0f540ee8082/www/src/store/index.js#L38-L39
Changed it

2021-06-10 07:01 UTC, StanBankras approved these changes

2021-06-10 07:14 UTC, StanBankras requested changes
Getter gets an error with mapping an undefined array when you have no trainings

2021-06-11 08:11 UTC, StanBankras approved these changes

2021-06-11 08:12 UTC, merged